SSOConfig:
    StageSPH:
        SSORegion: ap-southeast-1
        StartUrl: https://d-9667098aba.awsapps.com/start
        DefaultRegion: ap-southeast-1
        AuthUrlAction: open
DefaultRegion: ap-southeast-1
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: open-url-in-container
UrlExecCommand:
    - /Applications/Firefox.app/Contents/MacOS/firefox
    - "%s"
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ FirstItem .AccountName (.AccountAlias | nospace) }}:{{ .RoleName }}"
FullTextSearch: true


